apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: websocket-server
  labels:
    app: websocket-server
  annotations:
    haproxy.router.openshift.io/timeout: "300s"
    haproxy.router.openshift.io/websocket: "true"
spec:
  to:
    kind: Service
    name: websocket-server
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect